app = "musicdrop-monitor-fly"
primary_region = "ams"

[build]
  image = "node:18"

[env]
  NODE_ENV = "production"

[processes]
  app = "node index.js"

[[services]]
  processes = ["app"]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
