app = "musicdrop-fly"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[processes]
  app = "node index.js"

[experimental]
  auto_rollback = true

[checks]
  [checks.process]
    type = "process"
    interval = "30s"
    timeout = "5s"
